/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gg.bruce.irrigation

import com.fazecast.jSerialComm.SerialPort
import kotlin.system.exitProcess

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val serialPorts = SerialPort.getCommPorts()

    if(serialPorts.isEmpty()) {
        exitProcess(1)
    }

    val arduino = serialPorts.get(0)
    arduino.openPort()
    arduino.baudRate = 115200

    while (true) {
        while (arduino.bytesAvailable() > 0) {
            val readBuffer = ByteArray(arduino.bytesAvailable())
            for (byte in readBuffer) {
                print(byte.toChar())
            }
            println()
        }
    }
}
